on:  
  push:
    tags:
      - 'v*'

env:
  DOCKER_PROJECT_DIR: .

jobs:
  deploy-docker_hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ env.DOCKER_PROJECT_DIR }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
