on:  
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-latest
    container: ghcr.io/andtechstudios/iota-ci
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          export TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          export FILESIZE="14.2 MB"
          cat << EOF > exampleSite/metadata.json
          {
            "timestamp": "$TIMESTAMP",
            "displaySize": "$FILESIZE"
          }
          EOF
      - run: |
          cd exampleSite
          export BASE_URL="https://andtechstudios.github.io/iota"
          export IOTA_APP_URL="https://github.com/andtechstudios/iota/build.txt"
          export IOTA_DOWNLOAD_URL="itms-services://?action=download-manifest&url=https://github.com/andtechstudios/iota/blob/master/manifest.plist"
          export IOTA_APP_TITLE="My Cool App"
          envsubst < index.html > temp.html && mv temp.html index.html
          envsubst < manifest.plist > temp.plist && mv temp.plist manifest.plist
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: exampleSite
